package com.devtrace.studio.common;

public enum TraceEventType {
    JVM_STARTED,
    AGENT_ATTACHED,
    CLASS_TRANSFORMED,
    CLASS_LOADING_SNAPSHOT,
    SPRING_APPLICATION_RUN,
    SPRING_LIFECYCLE,
    BEAN_CREATION,
    BEAN_NODE,
    BEAN_EDGE,
    AUTO_CONFIGURATION,
    HTTP_REQUEST,
    HTTP_RESPONSE,
    SPAN_STARTED,
    SPAN_FINISHED,
    METHOD_INVOCATION,
    ASYNC_SCHEDULED,
    ASYNC_EXECUTION,
    DATABASE_QUERY,
    EXTERNAL_CALL,
    ERROR
}

